#
# list of targets generated by 'nexus build' which android integration depends on, we include
# the kernel modules in there as well as we bundle them with the 'nexus' build.  if nexus was
# opened-source, those kernel modules would not be needed as we could build the functionality
# directly into the kernel (exception being 'gator' which is third party).
#

REFSW_TARGET_LIST := \
	/${NEXUS_BIN_DIR}/libnexus.so \
	/${NEXUS_BIN_DIR}/libnexus_static.a \
	/${NEXUS_BIN_DIR}/libnxclient.so \
	/${NEXUS_BIN_DIR}/libnxserver.a \
	\
	${NEXUS_BIN_DIR}/nexus.ko \
	${NEXUS_BIN_DIR}/bcmnexusfb.ko \
	${NEXUS_BIN_DIR}/nx_ashmem.ko \
	${NEXUS_BIN_DIR}/droid_pm.ko \
	\
	${NEXUS_BIN_DIR}/gator.ko
