#
# list of targets generated by 'bcm_refsw.mk' which android integration depends on.
#

REFSW_TARGET_LIST := \
	${NEXUS_BIN_DIR}/bcmnexusfb.ko \
	${NEXUS_BIN_DIR}/libnexus_client.so \
	${NEXUS_BIN_DIR}/libnexus.so \
	${NEXUS_BIN_DIR}/libnexus_static.a \
	${NEXUS_BIN_DIR}/libnxclient_local.so \
	${NEXUS_BIN_DIR}/libnxclient.so \
	${NEXUS_BIN_DIR}/libnxserver.a \
	${NEXUS_BIN_DIR}/libmagnum.a \
	${NEXUS_BIN_DIR}/nexus.ko \
	${NEXUS_BIN_DIR}/nx_ashmem.ko
