ifneq ($(REFSW_DEFS_EXPORTED),y)

BRCMSTB_ANDROID_VENDOR_PATH     := ${ANDROID_TOP}/${BCM_VENDOR_STB_ROOT}
BRCMSTB_ANDROID_DRIVER_PATH     := ${BRCMSTB_ANDROID_VENDOR_PATH}/drivers

ifeq ($(OUT_DIR_COMMON_BASE),)
BRCMSTB_ANDROID_OUT_PATH    := ${ANDROID_TOP}/out
else
BRCMSTB_ANDROID_OUT_PATH    := ${OUT_DIR_COMMON_BASE}/$(notdir $(PWD))
endif

ifeq ($(PRODUCT_OUT),)
ifeq ($(OUT_DIR_COMMON_BASE),)
PRODUCT_OUT := out/target/product/${ANDROID_PRODUCT_OUT}
else
PRODUCT_OUT := ${OUT_DIR_COMMON_BASE}/$(notdir $(PWD))/target/product/${ANDROID_PRODUCT_OUT}
endif
endif

ifeq ($(OUT_DIR_COMMON_BASE),)
PRODUCT_OUT_FROM_TOP := ${ANDROID_TOP}/${PRODUCT_OUT}
export ANDROID_OUT_DIR := ${ANDROID_TOP}/out
else
PRODUCT_OUT_FROM_TOP := ${PRODUCT_OUT}
export ANDROID_OUT_DIR := ${OUT_DIR_COMMON_BASE}/$(notdir $(PWD))
endif
export LINUX_OUT := ${ANDROID_OUT_DIR}/target/product/${ANDROID_PRODUCT_OUT}/obj/FAKE/kernel

BRCM_NEXUS_INSTALL_PATH := ${BRCMSTB_ANDROID_VENDOR_PATH}/bcm_platform

NEXUS_TOP       := ${REFSW_BASE_DIR}/nexus
ROCKFORD_TOP    := ${REFSW_BASE_DIR}/rockford
BSEAV_TOP       := ${REFSW_BASE_DIR}/BSEAV
B_REFSW_TOOLCHAINS_INSTALL := ${BRCMSTB_ANDROID_OUT_PATH}/target/product/${ANDROID_PRODUCT_OUT}/obj/FAKE/refsw/toolchains/
B_REFSW_OBJ_ROOT := ${BRCMSTB_ANDROID_OUT_PATH}/target/product/${ANDROID_PRODUCT_OUT}/obj/FAKE/refsw/obj.$(NEXUS_PLATFORM)
B_BOLT_OBJ_ROOT  := ${BRCMSTB_ANDROID_OUT_PATH}/target/product/${ANDROID_PRODUCT_OUT}/obj/FAKE/bolt
B_DHD_OBJ_ROOT   := ${BRCMSTB_ANDROID_OUT_PATH}/target/product/${ANDROID_PRODUCT_OUT}/obj/FAKE/dhd
export B_REFSW_CROSS_COMPILE := ${B_REFSW_TOOLCHAINS_INSTALL}
NEXUS_BIN_DIR   := $(B_REFSW_OBJ_ROOT)/nexus/bin
export NEXUS_TOP ROCKFORD_TOP BSEAV_TOP B_REFSW_OBJ_ROOT NEXUS_BIN_DIR B_BOLT_OBJ_ROOT B_DHD_OBJ_ROOT

include ${NEXUS_TOP}/platforms/common/build/nexus_platforms.inc
export BCHP_CHIP

REFSW_DEFS_EXPORTED := y
export REFSW_DEFS_EXPORTED

endif
